### ISSUE TITLE
gyp: binding.gyp not found

### ISSUE THREAD

**Issue by clubajax** [Vidyo/vidyo.io-connector-electron#6]
I followed the instructions, but the app will not build: 
```
➜  VidyoClient-OSXSDK node-gyp rebuild     
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@12.10.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/mike/.nvm/versions/node/v12.10.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mike/Sites/VidyoClient-OSXSDK/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mike/.nvm/versions/node/v12.10.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mike/Library/Caches/node-gyp/12.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/mike/Library/Caches/node-gyp/12.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/mike/.nvm/versions/node/v12.10.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/mike/Library/Caches/node-gyp/12.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/mike/Sites/VidyoClient-OSXSDK',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /Users/mike/Sites/VidyoClient-OSXSDK) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/mike/.nvm/versions/node/v12.10.0/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/mike/.nvm/versions/node/v12.10.0/bin/node" "/Users/mike/.nvm/versions/node/v12.10.0/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/mike/Sites/VidyoClient-OSXSDK
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok 
```

**Comment by tmelko-vidyo** [comment]
This issue is related to node-gyp and npm configurations rather than to this electron sample.
I would suggest to clean npm and reinstall node-gyp.
Have a look at the clean build console attached with the same node-gyp version.
[console.log](https://github.com/Vidyo/vidyo.io-connector-electron/files/3932269/console.log)
