### ISSUE TITLE
ABI Stability issue - Electron@6.1.7 & Node@10.15.3

### ISSUE THREAD

**Issue by hphuong209** [Vidyo/vidyo.io-connector-electron#7]
I cannot achieve to compile the VidyoAddon for Electron 6.1.7. The error log is given below.
I suppose that it could be an ABI issue. Any idea to fix it, please?
Thanks.

```
gyp info using node-gyp@6.1.0
gyp info using node@10.15.3 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\User\.windows-build-tools\python27\python.exe"
.............
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  VidyoAddon.cc
  win_delay_load_hook.cc
c:\users\user\.electron-gyp\6.1.9\include\node\v8.h(8205): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\VidyoAddon.cc) [C:\Users\User\Documents\electron\invoelectron\build\VidyoAddon.vcxproj]
  c:\users\user\.electron-gyp\6.1.9\include\node\v8.h(6667): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\VidyoAddon.cc)
c:\users\user\.electron-gyp\6.1.9\include\node\v8.h(8214): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\VidyoAddon.cc) [C:\Users\User\Documents\electron\invoelectron\build\VidyoAddon.vcxproj]
  c:\users\user\.electron-gyp\6.1.9\include\node\v8.h(6667): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\VidyoAddon.cc)

c:\users\user\documents\electron\invoelectron\vidyoaddon.cc(19): error C2664: 'void v8::ReturnValue<T>::Set(uint32_t)': cannot convert argument 1 from 'v8::MaybeLocal<v8::String>' to 'bool' [C:\Users\User\Documents\electron\invoelectron\build\VidyoAddon.vcxproj]
          with
          [
              T=v8::Value
          ]

  c:\users\user\documents\electron\invoelectron\vidyoaddon.cc(19): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
........
c:\users\user\documents\electron\invoelectron\vidyoaddon.cc(32): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declared deprecated [C:\Users\User\Documents\electron\invoelectron\build\VidyoAddon.vcxproj]
  c:\users\user\.electron-gyp\6.1.9\include\node\v8.h(2964): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\User\Documents\electron\invoelectron\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\Documents\\electron\\invoelectron\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=6.1.9" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\User\Documents\electron\invoelectron
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

```

**Comment by hphuong209** [comment]
By updating VidyoAddon.cc as below, I finally can compile the addon. 
```
#include <nan.h>
#include "Lmi/VidyoClient/VidyoClientElectron.h"
#include "Lmi/Os/LmiMallocAllocator.h"
#include <string>

void VidyoAddonInit(const Nan::FunctionCallbackInfo<v8::Value>& args)
{
    // v8::Local<v8::Context> context = args.GetIsolate()->GetCurrentContext();
    if (VidyoClientElectronInit())
        args.GetReturnValue().Set(Nan::New(true));
    else
        args.GetReturnValue().Set(Nan::New(false));
}
//
void VidyoAddonUninit(const Nan::FunctionCallbackInfo<v8::Value>& args)
{
    VidyoClientElectronUninit();
}
//
void VidyoAddonDispatch(const Nan::FunctionCallbackInfo<v8::Value>& args)
{
  // v8::Isolate* isolate = args.GetIsolate();
  // v8::String::Utf8Value data(args[0]->ToString());
  Nan::Utf8String data(args[0]);
  std::string request(*data);
  LmiString requestSt;
  LmiString responseSt;
  LmiAllocator *alloc;

  alloc = LmiMallocAllocatorGetDefault();
  LmiStringConstructCStr(&requestSt, request.c_str(), alloc);
  LmiStringConstructDefault(&responseSt, alloc);
  VidyoClientElectronDispatch(&requestSt, &responseSt);


  args.GetReturnValue().Set(Nan::New(LmiStringCStr(&responseSt)).ToLocalChecked());
}

void init(v8::Local<v8::Object> exports) {
    v8::Local<v8::Context> context = exports->CreationContext();

    exports->Set(context,
        Nan::New("VidyoAddonInit").ToLocalChecked(),
        Nan::New<v8::FunctionTemplate>(VidyoAddonInit)
        ->GetFunction(context)
        .ToLocalChecked()
    );

    exports->Set(context,
        Nan::New("VidyoAddonUninit").ToLocalChecked(),
        Nan::New<v8::FunctionTemplate>(VidyoAddonUninit)
        ->GetFunction(context)
        .ToLocalChecked()
    );

    exports->Set(context,
        Nan::New("VidyoAddonDispatch").ToLocalChecked(),
        Nan::New<v8::FunctionTemplate>(VidyoAddonDispatch)
        ->GetFunction(context)
        .ToLocalChecked()
    );

    // NODE_SET_METHOD(exports, "VidyoAddonInit", VidyoAddonInit);
    // NODE_SET_METHOD(exports, "VidyoAddonUninit", VidyoAddonUninit);
    // NODE_SET_METHOD(exports, "VidyoAddonDispatch", VidyoAddonDispatch);
}


NODE_MODULE(VidyoAddon, init)

```
